blank_issues_enabled: true
contact_links:
  - name: IntellectualSites Github
    url: https://github.com/IntellectualSites/PlotSquared
    about: PLEASE POST ISSUES THERE. WE DO NOT HANDLE BUG REPORTS
  - name: IntellectualSites Discord
    url: https://discord.gg/intellectualsites
    about: Our support Discord, please ask questions and seek support here.
  - name: PlotSquared Wiki
    url: https://intellectualsites.gitbook.io/plotsquared/
    about: Take a look at the wiki page for instructions how to setup PlotSquared and use its commands.
